name: Rust

on:
  push:
    branches: ["master", "tests"]
  pull_request:
    branches: ["master", "tests"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libsdl2-dev

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test -p chip8 opcode_tests --verbose
